### ISSUE TITLE
I'm sorry

### ISSUE THREAD

**Issue by TheSmallTeaBoi** [miacate/VoidBot#1]
I'm sorry, but can't you see the **incredibly ass** code this thing is? Aren't you **ashamed** of **even writting it**? Let alone publishing it.

**Comment by miacate** [comment]
lmao, I've written worse code that I've been proud of

**Comment by miacate** [comment]
Just look at spotbash, it's a bunch of fucking curl calls, lmfao

**Comment by TheSmallTeaBoi** [comment]
Fair enough, still this is actual ass code

**Comment by miacate** [comment]
This is worse code,,,
